Updated readme github buttons
GoogleCloudPlatform/gke-tracing-demo pull request #12
Opened 2018-12-19 22:19 UTC by swathiswaminathan

Added a 'open in cloudshell' feature into the Readme

2018-12-20 17:00 UTC, chrislovecnm approved these changes
Thanks

2018-12-26 18:17 UTC, chrislovecnm requested changes

2018-12-26 18:17 UTC, chrislovecnm commented on README.md
> +Click the button below to run the demo in a [Google Cloud Shell][10].
Please update

2018-12-27 21:06 UTC, emailbob commented
test this please

2018-12-27 21:19 UTC, emailbob commented
test this please

2018-12-27 21:37 UTC, emailbob approved these changes
Looks good

2018-12-27 21:39 UTC, emailbob commented on README.md
> +Click the button below to run the demo in a [Google Cloud Shell][10].
This has been updated

2018-12-27 22:41 UTC, chrislovecnm approved these changes

2018-12-27 22:42 UTC, merged